ALTER TABLE t_p9932520_itc_siberia_website.contact_requests
ADD COLUMN IF NOT EXISTS consent_given BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS consent_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS consent_ip VARCHAR(64) NULL,
ADD COLUMN IF NOT EXISTS consent_source VARCHAR(255) NULL;